### ISSUE TITLE
[Question] Can I use an icon from your mod?

### ISSUE THREAD

**Issue by Xman1109** [brevven/carbon#13]
Hey there,

I absolutely love your mods and the dedication you put into them. I'm currently working on updating one of my own mods, and I was in need of an icon for nuclear fuel pellets. That's when I remembered the amazing [graphite-2 icon](https://github.com/brevven/carbon/blob/main/graphics/icons/graphite-2.png) from your mod, which I really like.
I was wondering if I could use it in my mod, with a few modifications to the colors and such. Although all of your mods are licensed under MIT, I figured it wouldn't hurt to ask for permission first.

Edit: If you want to discuss this in private, then here is my discord: X_Man1109#6160

**Comment by brevven** [comment]
Hello, thanks for asking. Sure thing, feel free to use it in your mod!
